---

##
# Check if python versions are already installed
##

- name: py24 | Check that py24 is still not installed
  become: true
  stat: path="{{ py24_bin }}"
  register: py24_already_installed
  ignore_errors: True

- name: py26 | Check that py26 is still not installed
  become: true
  stat: path="{{ py26_bin }}"
  register: py26_already_installed
  ignore_errors: True

- name: py27 | Check that py27 is still not installed
  become: true
  stat: path="{{ py27_bin }}"
  register: py27_already_installed
  ignore_errors: True

- name: py35 | Check that py35 is still not installed
  become: true
  stat: path="{{ py35_bin }}"
  register: py35_already_installed
  ignore_errors: True

##
# Download
##

- name: py24 | Download
  get_url:
    url="{{ py24_url }}"
    dest="{{ py24_tar_file }}"
    checksum="md5:{{ py24_md5 }}"
  when: python_24 and py24_already_installed.stat.exists == false

- name: py26 | Download
  get_url:
    url="{{ py26_url }}"
    dest="{{ py26_tar_file }}"
    checksum="md5:{{ py26_md5 }}"
  when: python_26 and py26_already_installed.stat.exists == false

- name: py27 | Download
  get_url:
    url="{{ py27_url }}"
    dest="{{ py27_tar_file }}"
    checksum="md5:{{ py27_md5 }}"
  when: python_27 and py27_already_installed.stat.exists == false

- name: py35 | Download
  get_url:
    url="{{ py35_url }}"
    dest="{{ py35_tar_file }}"
    checksum="md5:{{ py35_md5 }}"
  when: python_35 and py35_already_installed.stat.exists == false

##
# Uncompress
##

- name: py24 | Uncompress
  unarchive:
    src={{ py24_tar_file }}
    dest=/tmp
    copy=no
    creates="{{ py24_sources }}"
  when: python_24 and py24_already_installed.stat.exists == false

- name: py26 | Uncompress
  unarchive:
    src={{ py26_tar_file }}
    dest=/tmp
    copy=no
    creates="{{ py26_sources }}"
  when: python_26 and py26_already_installed.stat.exists == false

- name: py27 | Uncompress
  unarchive:
    src={{ py27_tar_file }}
    dest=/tmp
    copy=no
    creates="{{ py27_sources }}"
  when: python_27 and py27_already_installed.stat.exists == false

- name: py35 | Uncompress
  unarchive:
    src={{ py35_tar_file }}
    dest=/tmp
    copy=no
    creates="{{ py35_sources }}"
  when: python_35 and py35_already_installed.stat.exists == false

##
# Compile and install
##

- name: py24 | Compile and install
  become: true
  command: "{{ item }}"
  args:
    chdir: "{{ py24_sources }}"
  with_items:
    - "./configure --prefix {{ py24_install }}"
    - make
    - make install
  when: python_24 and py24_already_installed.stat.exists == false

- name: py26 | Compile and install
  become: true
  command: "{{ item }}"
  args:
    chdir: "{{ py26_sources }}"
  with_items:
    - "./configure --prefix {{ py26_install }}"
    - make
    - make install
  when: python_26 and py26_already_installed.stat.exists == false

- name: py27 | Compile and install
  become: true
  command: "{{ item }}"
  args:
    chdir: "{{ py27_sources }}"
  with_items:
    - "./configure --prefix {{ py27_install }}"
    - make
    - make install
  when: python_27 and py27_already_installed.stat.exists == false

- name: py35 | Compile and install
  become: true
  command: "{{ item }}"
  args:
    chdir: "{{ py35_sources }}"
  with_items:
    - "./configure --prefix {{ py35_install }}"
    - make
    - make install
  when: python_35 and py35_already_installed.stat.exists == false
